"""
Configuration constants for PDF to Audio converter
"""

import os
from pathlib import Path

# Project paths
PROJECT_ROOT = Path(__file__).parent
MODELS_DIR = PROJECT_ROOT / "models"
DEFAULT_VOICE_MODEL = MODELS_DIR / "en_US-lessac-medium.onnx"

# PDF Extraction settings
PDF_EXTRACTION_ENGINE = "pymupdf"  # or "pdfplumber"
CONFIDENCE_THRESHOLD = 0.7  # Minimum confidence for extraction quality

# Text preprocessing settings
MAX_CHUNK_LENGTH = 500  # Maximum characters per TTS chunk
MIN_CHUNK_LENGTH = 50   # Minimum characters per TTS chunk
SENTENCE_ENDINGS = ['.', '!', '?', '。', '！', '？']
PARAGRAPH_BREAK_MARKER = "\n\n"

# Abbreviations to expand for natural speech
ABBREVIATIONS = {
    'Dr.': 'Doctor',
    'Mr.': 'Mister',
    'Mrs.': 'Misses',
    'Ms.': 'Miss',
    'Prof.': 'Professor',
    'Sr.': 'Senior',
    'Jr.': 'Junior',
    'Fig.': 'Figure',
    'vs.': 'versus',
    'etc.': 'et cetera',
    'e.g.': 'for example',
    'i.e.': 'that is',
    'Inc.': 'Incorporated',
    'Ltd.': 'Limited',
    'Corp.': 'Corporation',
}

# TTS settings
DEFAULT_SPEECH_SPEED = 1.0
MIN_SPEECH_SPEED = 0.5
MAX_SPEECH_SPEED = 2.0
TTS_SAMPLE_RATE = 22050  # Piper default

# Audio output settings
OUTPUT_FORMAT = "m4b"
AUDIO_CODEC = "aac"
AUDIO_BITRATE = "64k"
CHAPTER_TITLE_TEMPLATE = "Page {page_number}"

# M4B metadata defaults
DEFAULT_METADATA = {
    'album': 'PDF Audiobook',
    'genre': 'Audiobook',
    'comment': 'Generated by PDF to Audio Converter',
}

# Extraction confidence heuristics
BLANK_PAGE_CHAR_THRESHOLD = 10  # Pages with fewer chars considered blank
CHAR_DROP_THRESHOLD = 0.5  # Alert if page has 50% fewer chars than average
MIN_PAGES_FOR_HEURISTICS = 3  # Minimum pages before running heuristics

# CLI settings
PROGRESS_BAR_ENABLED = True
QUIET_MODE = False

# Dependencies to check
REQUIRED_BINARIES = ['ffmpeg']

# Error messages
ERROR_MESSAGES = {
    'pdf_not_found': 'PDF file not found: {path}',
    'voice_model_not_found': 'Voice model not found: {path}',
    'ffmpeg_not_found': 'ffmpeg binary not found. Please install ffmpeg.',
    'invalid_pdf': 'Invalid or corrupted PDF file: {path}',
    'extraction_failed': 'Failed to extract text from PDF',
    'tts_failed': 'Text-to-speech conversion failed',
    'audio_conversion_failed': 'Audio conversion to M4B failed',
    'no_text_extracted': 'No text could be extracted from the PDF. It may be scanned or image-based.',
}

# Success messages
SUCCESS_MESSAGES = {
    'conversion_complete': 'Conversion completed successfully: {output}',
    'test_complete': 'Random page test completed: {output}',
    'environment_ok': 'All dependencies are installed and working correctly.',
}

# Logging configuration
LOG_FORMAT = '%(asctime)s - %(levelname)s - %(message)s'
LOG_LEVEL = 'INFO'
